routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Authentication routes*/
// Route::get('auth/login', 'Auth\AuthController@getLogin');
// Route::post('auth/login', 'Auth\AuthController@postLogin');
// Route::get('auth/logout', 'Auth\AuthController@getLogout');

/* Registration Routes */
// Route::get('auth/register', 'Auth\AuthController@getRegister');
// Route::post('auth/register', 'Auth\AuthController@postRegister');


/* Route to blog specific post*/
Route::get('blog/{slug}',['as'=>'blog.single','uses' => 'BlogController@getSingle'])->where('slug','[\w\d\-\_]+');

/* Route to all list of blog posts*/
Route::get('blog',['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

/* About route*/
Route::get('about', 'PagesController@getAbout');

/* Contact route*/
Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

/* Subscribe Route*/
Route::get('subscribe', 'PagesController@getSub');
Route::post('subscribe', 'PagesController@postSub');

Route::get('/', 'PagesController@getIndex');

/* Tell laravel that we are managing resource*/
Route::resource('posts','PostsController');

/* Route to categories*/
Route::resource('categories','CategoryController',['except'=>['create']]);
Route::resource('tags','TagController',['except'=>['create']]);

/* Comments route */
Route::post('comments/{post_id}', ['uses'=>'CommentsController@store', 'as' => 'comments.store']);
Route::get('comments/{id}/edit',['uses'=>'CommentsController@edit', 'as' => 'comments.edit']);
Route::put('comments/{id}',['uses'=>'CommentsController@update', 'as' => 'comments.update']);
Route::delete('comments/{id}',['uses'=>'CommentsController@destroy', 'as' => 'comments.destroy']);
Route::get('comments/{id}/delete',['uses'=>'CommentsController@delete', 'as' => 'comments.delete']);


Route::get('profile', 'HomeController@profile');




/*Home page route showing 4 of oldest articles (to edit as 4 featured articles when I update db*/
Route::get('/home', 'ArticlesController@showFeaturedArticles');


/*Articles List route display all articles in paginate*/
Route::get('/articles', 'ArticlesController@showArticles');






/*Just to check if layout works*/
Route::get('/layout', function () {
    return view('applayout');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function articles() {
   		return $this->belongsTomany('App\Article');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Session;

class TagController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('tags.index')->withTags($tags);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name'=> 'required|max:255'
        ));

        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        Session::flash('success','New Tag was successfully created!');

        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tag = Tag::find($id);
        return view('tags.show')->withTag($tag);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('tags.edit')->withTag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        $this->validate($request,['name' => 'required|max:255']);
        $tag->name = $request->name;
        $tag->save();

        Session::flash('success', 'This tag has been successfully updated!');
        return redirect()->route('tags.show', $tag->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->articles()->detach();

        $tag->delete();

        Session::flash('success', 'Tag was deleted successfully');
        return redirect()->route('tags.index');
    }
}

resources/views/tags/edit.blade.php
@extends('applayout')

@section('title', '| Edit This Tag')

@section('banner')
    <header class="masthead" style="background-image: url(../../)">

      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading small-banner">
              @include('partials._messages')
              <h1 class="text-center">Edit This Tag</h1>
              <div class="divider"></div>
              <span class="subheading">{{ $tag->name }}</span>
            </div>
          </div>
        </div>
      </div>
    </header>
@endsection

@section('main')
    <!-- Post Content -->
    <article>

       <div class="container">
        <div class="row text-center margin-t">
          <div class="col-lg-8 col-md-10 mx-auto">
             <p><small>Last Updated: {{ date('M j, Y h:ia',strtotime($tag->created_at )) }}</small></p>

          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
              <div class="divider"></div>
              <div class="form-signin background-container" style="max-width: 100%;">
           		{!! Form::model($tag, ['route' => ['tags.update',$tag->id], 'method' => 'PUT']) !!}
                    {{ Form::label('name','Tag Name:',['class' => 'margin-t']) }}
                    {{ Form::text('name', null, ['class' => 'form-control', 'required' => '']) }}
  
              </div>
             
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row text-center margin-t">
          <div class="col-lg-8 col-md-10 mx-auto">

            {!! Html::linkRoute('tags.show','Cancel',array($tag->id),array('class' => 'btn btn-raised btn-danger')) !!}

             {{ Form::submit('Save Changes', ['class' => 'btn btn-raised btn-success', 'style' => 'cursor:pointer'] ) }}

	         {!! Form::close() !!}

          </div>
        </div>
        <div class="divider"></div>
      </div>

    </article>



 @endsection

resources/views/tags/index.blade.php
@extends('applayout')


@section('title', '| All Tags')


@section('banner')
    <header class="masthead" style="background-image: url('img/blog2.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading small-banner">
           		@include('partials._messages')
              <h1>All Tags</h1>
              <span class="subheading">Manage Tags Here.</span>
            </div>
          </div>
        </div>
      </div>
    </header>
@endsection

@section('main')

    <!-- Main Content -->
  <main class="background-container">

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
       	<h3 class="text-center margin-t">Add New Tag</h3>
        <div class="divider"></div>
            	{!! Form::open(['route' => 'tags.store', 'method' => 'POST', 'class' => 'w-clearfix']) !!}
            		
            		{{ Form::text('name', null, ['class' => 'field w-input', 'placeholder' => 'Type New Tag Here', 'required']) }}
            		{{ Form::submit('Add Tag', ['class' => 'submit-button w-button btn-primary']) }}
            	{!! Form::close() !!}

          <table id="box-table-a" summary="Categories">
              <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">#</th>
                    <th scope="col">Tag Name</th>
                    <th scope="col">Created At</th>
                  </tr>
              </thead>
              <tbody>

                @foreach($tags as $tag)
                  <tr>
                    <td></td>
                    <td>{{ $tag->id }}</td>
                    <td>
                      <a href="{{ route('tags.show', $tag->id)}}" class="label label-primary">{{ $tag->name }}</a>
                    </td>
                    <td>{{ $tag->created_at }}</td>
                  </tr>

                @endforeach
              </tbody>
          </table>

          <!-- Pager -->
          <div class="clearfix">
          	
          </div>
        </div>
      </div>
    </div>
  </main>


  @endsection

resources/views/tags/show.blade.php
@extends('applayout')

@section('title', "| $tag->name Tag")

@section('banner')
    <header class="masthead" style="background-image: url(../)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading small-banner">
              @include('partials._messages')
              <h1>Manage Specific Tag</h1>
              <div class="divider"></div>
              <span class="subheading">All posts related to [ {{ $tag->name }} ] Tag</span>

            </div>
          </div>
        </div>
      </div>
    </header>
@endsection

@section('main')
    <article>

      <div class="container">
        <div class="row text-center margin-t">
          <div class="col-lg-8 col-md-10 mx-auto">
            
             
             <a href="{{ route('tags.edit',$tag->id) }}" class="btn btn-raised btn-info">Edit Tag</a>

             {!! Form::open(['route' => ['tags.destroy',$tag->id], 'method' => 'DELETE', 'style' => 'display: inline-block']) !!}

            {!! Form::submit('Delete',['class' => 'btn btn-raised btn-danger','style' => 'cursor: pointer' ]) !!}

            {!! Form::close() !!}

             <div class="divider"></div>
              <a href="{{ url('tags')}}" class="btn btn-raised btn-success"><< See All Tags</a>
             <div class="divider"></div>
             <p class="subheading"><h3 class="label label-choice">{{ $tag->name }}</h3> Tag <small>( {{ $tag->articles()->count() }} Posts )</small></p>
          </div>
        </div>
      </div>

    </article>

    <!-- Main Content -->
  <main class="background-container">

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">

          <table id="box-table-a" summary="tags listing">
              <thead>
                <tr>
                    <th scope="col">#</th>
                      <th scope="col">Post Title</th>
                      <th scope="col">Tags</th>
                      <th scope="col"></th>
                  </tr>
              </thead>
              <tbody>

                @foreach($tag->articles as $post)
                  <tr>
                    <td>{{ $post->id }}</td>
                    <td>
                      {{ substr($post->title, 0, 40) }}
                      {{ strlen($post->title) > 40 ? "..." : "" }}
                    </td>
                    <td>
                    	@foreach($post->tags as $tag1)
                    		<span class="label 
                              <?php if($tag1->id !== $tag->id) { 
                                echo 'label-primary';
                              } else {
                                echo 'label-choice';
                            } ?>">{{ $tag1->name }}</span>
                    	@endforeach
                    </td>
                    <td>
                      <a href="{{ route('posts.show',$post->id) }}" class="btn btn-info small-b">View</a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>

          <!-- Pager -->
          <div class="clearfix">
          	
          </div>
        </div>
      </div>
    </div>
  </main>

 @endsection