routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Authentication routes*/
// Route::get('auth/login', 'Auth\AuthController@getLogin');
// Route::post('auth/login', 'Auth\AuthController@postLogin');
// Route::get('auth/logout', 'Auth\AuthController@getLogout');

/* Registration Routes */
// Route::get('auth/register', 'Auth\AuthController@getRegister');
// Route::post('auth/register', 'Auth\AuthController@postRegister');


/* Route to blog specific post*/
Route::get('blog/{slug}',['as'=>'blog.single','uses' => 'BlogController@getSingle'])->where('slug','[\w\d\-\_]+');

/* Route to all list of blog posts*/
Route::get('blog',['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

/* About route*/
Route::get('about', 'PagesController@getAbout');

/* Contact route*/
Route::get('contact', 'PagesController@getContact');
Route::post('contact', 'PagesController@postContact');

/* Subscribe Route*/
Route::get('subscribe', 'PagesController@getSub');
Route::post('subscribe', 'PagesController@postSub');

Route::get('/', 'PagesController@getIndex');

/* Tell laravel that we are managing resource*/
Route::resource('posts','PostsController');

/* Route to categories*/
Route::resource('categories','CategoryController',['except'=>['create']]);
Route::resource('tags','TagController',['except'=>['create']]);

/* Comments route */
Route::post('comments/{post_id}', ['uses'=>'CommentsController@store', 'as' => 'comments.store']);
Route::get('comments/{id}/edit',['uses'=>'CommentsController@edit', 'as' => 'comments.edit']);
Route::put('comments/{id}',['uses'=>'CommentsController@update', 'as' => 'comments.update']);
Route::delete('comments/{id}',['uses'=>'CommentsController@destroy', 'as' => 'comments.destroy']);
Route::get('comments/{id}/delete',['uses'=>'CommentsController@delete', 'as' => 'comments.delete']);


Route::get('profile', 'HomeController@profile');




/*Home page route showing 4 of oldest articles (to edit as 4 featured articles when I update db*/
Route::get('/home', 'ArticlesController@showFeaturedArticles');


/*Articles List route display all articles in paginate*/
Route::get('/articles', 'ArticlesController@showArticles');






/*Just to check if layout works*/
Route::get('/layout', function () {
    return view('applayout');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/partials/_footer.blade.php
<!-- Footer -->
<footer class="dark main-section w-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        <h3 class="white text-center">Stay In Touch</h3>
        <div class="divider"></div>
        <div class="form-wrapper">
          <form method="POST" action="{{ url('subscribe') }}" id="email-form" name="email-form" data-name="Email Form" class="w-clearfix">
            {{ csrf_field() }}
            <input type="email" class="field w-input" maxlength="256" name="email" data-name="Email" placeholder="Enter your email address" id="email" required=""><input type="submit" value="Submit" data-wait="Please wait..." class="submit-button w-button">
          </form>

        </div>

        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-square fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-square fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-square fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Pearl Drv 2017. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

resources/views/partials/_head.blade.php
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Pearl Drv is a personal blog by Jhun Agustin. It is where I post all my interests in life. That includes sceneries, places, people and many others.">
    <meta name="author" content="">

    <title>Pearl Drv @yield('title')</title>

    <!-- Bootstrap core CSS -->
    <link href='{{ url("vendor/bootstrap/css/bootstrap.min.css") }}' rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href='{{ url("vendor/font-awesome/css/font-awesome.min.css") }}' rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">


    <!-- Custom styles for this template -->
    <link href='{{ url("css/style.css") }}' rel="stylesheet">

    <!-- Select2 CSS  -->
    <!-- <link href='path/to/select2.min.css' rel="stylesheet" /> -->
    {!! Html::style('css/select2.min.css') !!}

<!--  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>

  <script>tinymce.init({ selector:'textarea' });</script>

  -->

resources/views/partials/_messages.blade.php
@if (Session::has('success'))

	<div class="alert alert-success small" role="alert">
		<label for="alertmessage"><strong>Success:</strong> {{ Session::get('success') }}</label>
	</div>	

@endif

@if (count($errors)>0)
	
	<div class="alert alert-danger small" role="alert">
		<label><strong>Errors:</strong> {{ Session::get('success') }}</label>
		<ul class="">
		@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach
		</ul>
	</div>	

@endif

resources/views/partials/_nav.blade.php
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href='{{url("/")}}'>PEARL DRV</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars" id="nav-toggle"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
          <a class="nav-link" href='{{url("/")}}'>Home</a>
        </li>
        <li class="nav-item {{ Request::is('about') ? 'active' : '' }}">
          <a class="nav-link" href='{{url("/about")}}'>About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href='{{url("/blog")}}'>Blog Feed</a>
        </li>
        <li class="nav-item {{ Request::is('contact') ? 'active' : '' }}">
          <a class="nav-link" href='{{url("/contact")}}'>Contact</a>
        </li>

    @if (Auth::check())
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href='/'>{{ Auth::user()->name }}</a>
          <ul class="dropdown-menu">
            <li class="nav-item"><a class="nav-link" href="">Account</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ route('posts.index')}}">Posts</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ route('tags.index')}}">Tags</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ route('categories.index')}}">Categories</a></li>
            <li class="nav-item"><a class="nav-link" href="">Archive</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form></li>
          </ul>
        </li>
    @else
        <li class="nav-item">
          <a href="{{ route('login') }}" class="nav-link">Login</a>
        </li>
    @endif

      </ul>
    </div>
  </div>
</nav>